### PR TITLE
fix(oxygen-compatibility): fix to location of unevaluatedProperties based on oxygen feedback

### PR DESCRIPTION
**Pull request by iyoung**
Small change which is semantically identical to the original but will already validate in oxygen

### CODE REVIEW

**Comment by bquinn** [comment]
I can confirm that this works for me. Tests pass in Python, Javascript (ajv) and Oxygen on my machine!

**Comment by jolla56** [comment]
In my oxygen it does not behave correct when I insert a non-existing property inside an associations object.

**Comment by jolla56** [comment]
I just noticed, why do we declare name as an array of string?
             "name": {
                "title": "Name (of associated object)",
                "description": "Human-readable name of the associated object.",
                "type": [
                  "string"
                ]
              }

**Comment by bquinn** [comment]
that's strange, it seems correct for me. I took your example
tt_text_image_2.json and added a bad property into the first association:

        { "name": "a001",
          "by": "Karl Melander/TT",
          "descriptions": [{"value": "En stor internationell försvarsövning
planeras 2023 med fokus på södra Sverige och Gotland. Arkivbild från
militärövningen Aurora 17."}],
          "representationtype": "partial",
          "type": "picture",
          "bad": "property",
          "uri": "http://tt.se/media/image/sdlk2sirkPaauM",


Then I used Oxygen to validate against the new 2.1 schema, and got the
expected error:


System ID:
/Users/brendan/dev/iptc/newsinjson/examples/2.1/tt_text_image_2.json
Main validation file:
/Users/brendan/dev/iptc/newsinjson/examples/2.1/tt_text_image_2.json
Schema:
/Users/brendan/dev/iptc/newsinjson/specification/ninjs-schema_2.1.json
Engine name: JSON Validator
Severity: error
Description: #/associations/0/bad: extraneous key [bad] is not permitted
Start location: 65:11
End location: 65:16

**Comment by bquinn** [comment]
you're right, that's a bug left from when I was playing with different ways
of making it work.

It doesn't seem to affect the test outcomes though. Even if I leave it in
and do "name": false or "name": 1234 validation fails the way we would
expect (expected type String, found boolean / found integer)

But either way it shouldn't be there, so I'll fix it and commit to this
branch.

**Pull request merged**
